core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('mama_fua.urls'))
]

mama_fua/urls.py
"""Defines Urls for full_belly_project"""


from django.urls import path
from . import views

app_name = 'mama_fua'

urlpatterns = [

    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('cloth_details/', views.cloth_details, name='cloth_details'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('history/', views.history, name='history'),
    path('cart/', views.cart, name='cart'),
    path('create_order/', views.create_order, name='create_order'),

]

users/urls.py
"""Defines Urls for users"""


from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [

    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),

]

mama_fua/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'mama_fua/dashboard.html')


def index(request):
    return render(request, 'mama_fua/index.html')


def cloth_details(request):
    return render(request, 'mama_fua/cloth_details.html')


def cart(request):
    return render(request, 'mama_fua/cart.html')


def checkout(request):
    return render(request, 'mama_fua/checkout.html')


def confirm_order(request):
    return render(request, 'mama_fua/confirm_order.html')


def history(request):
    return render(request, 'mama_fua/history.html')


def create_order(request):
    return render(request, 'mama_fua/create_order.html')

users/views.py
from django.shortcuts import render


def login(request):
    return render(request, 'registration/login.html')


def signup(request):
    return render(request, 'registration/register.html')

mama_fua/templates/mama_fua/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load django_bootstrap5 %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    <meta charset="utf-8" content="width=device-width, initial-scale=1.0"
          name="viewport">
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</head>
<body bgcolor="#A0E7E5">

<header>
    <div>
        <section>
            <nav class="navbar navbar-expand-xl navbar-dark bg-dark flex-wrap">
                <div class="container-fluid">
                    <div class="d-flex w-100 align-items-center">
                        <a class="navbar-brand" href="{% url 'mama_fua:home' %}">
                            <img class="img-fluid" src="https://i.ibb.co/KxSnLjf/logo.png" alt="logo" width="50" height="50">
                        </a>
                        <button class="navbar-burger navbar-toggler bg-primary ms-auto" type="button">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse ms-12">
                            <ul class="navbar-nav">

                                <li class="nav-item">
                                  <a class="nav-link d-flex align-items-center" href="{% url 'mama_fua:home' %}">
                                      <i class="fa-solid fa-house-chimney fa-lg"></i>
                                    <span class="small ms-2" style="font-size: 15px;">Home</span>
                                  </a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link d-flex align-items-center" href="{% url 'mama_fua:create_order' %}">
                                      <i class="fa-solid fa-shirt fa-lg"></i>
                                      <span class="small ms-2" style="font-size: 15px;">Laundry Services</span>
                                  </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center" href="{% url 'mama_fua:history' %}">
                                        <i class="fa-solid fa-clock-rotate-left fa-lg"></i>
                                        <span class="small ms-2" style="font-size: 15px;">History</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link d-flex align-items-center" href="{% url 'mama_fua:cart' %}">
                                      <i class="fa-solid fa-cart-shopping fa-lg"></i>
                                      <span class="small ms-2" style="font-size: 15px;">Laundry Basket</span>
                                  </a>
                                </li>


                            </ul>
                            <ul class="navbar-nav me-6 ms-auto">
                                <li class="nav-item me-6">
                                </li>
                                <li class="nav-item px-0">
                                </li>
                            </ul>
                            <div>
                                <button class="btn p-0 fw-normal text-end d-flex align-items-center">
                                    <div class="me-3">
                                        <p class="mb-0 small text-white" style="font-size: 18px;">Moses Musemi</p>
                                    </div>
                                    <div class="me-2">
                                        <img alt=""
                                             class="img-fluid rounded-circle"
                                             src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;crop=faces&amp;fit=crop&amp;h=128&amp;w=128"
                                             style="width: 40px; height: 40px; object-fit: cover;">
                                    </div>

                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="position-relative navbar-menu d-none" style="z-index: 9999;">
                <div class="navbar-backdrop position-fixed top-0 end-0 bottom-0 start-0 bg-dark"
                     style="opacity: .5"></div>
            </div>
        </section>
    </div>
</header>

{% block content %}

{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

mama_fua/templates/mama_fua/cart.html
{% extends 'mama_fua/base.html'%}

{% block title %}Cart{% endblock %}

{% block content %}

<section class="py-20 bg-light overflow-hidden">
  <div class="container">
    <div class="p-8 p-lg-20 bg-white">
      <h2 class="mb-8">Laundry Basket</h2>
      <p class="mb-10 mb-md-16 text-secondary">Below are your Laundry Basket Contents</p>
      <div class="row mb-8 align-items-center justify-content-between">
        <div class="col-12 col-lg-auto mb-8 mb-lg-0 d-flex flex-wrap align-items-center">
          <div class="d-flex align-items-center justify-content-center mb-4 mb-lg-0 bg-light" style="height: 128px;">
            <img class="img-fluid h-100" style="object-fit: contain;" src="https://i.ibb.co/qpgTwSf/blanket.png" alt="blanket">
          </div>
          <div class="col-12 col-md-auto ps-md-8">
            <h3 class="mb-2 lead fw-bold">Blanket Cleaning</h3>
            <p class="mb-8 text-secondary">Wash & Fold</p>
          </div>
        </div>
        <div class="d-flex col-12 col-lg-auto justify-content-between align-items-center flex-lg-column">
          <p class="mb-lg-12 text-end h6 text-info">ksh. 300</p>
          <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
            <button class="btn px-0 py-2">
              <svg width="12" height="2" viewBox="0 0 12 2" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="12" width="2" height="12" transform="rotate(90 12 0)" fill="currentColor"></rect></g></svg>
            </button>
            <input class="form-control px-2 py-4 text-center text-md-end border-0" style="width: 48px;" type="number" placeholder="1" min="0" onchange="checkZero(this);">
            <button class="btn px-0 py-2">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="5" width="2" height="12" fill="currentColor"></rect><rect x="12" y="5" width="2" height="12" transform="rotate(90 12 5)" fill="currentColor"></rect></g></svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="removeItemModal" tabindex="-1" aria-labelledby="removeItemModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="removeItemModalLabel">Remove item from basket?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to remove this item from your basket?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <button id="removeButton" type="button" class="btn btn-danger">Remove</button>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-12 align-items-center justify-content-between">
        <div class="col-12 col-lg-auto mb-8 mb-lg-0 d-flex flex-wrap align-items-center">
          <div class="d-flex align-items-center justify-content-center mb-4 mb-lg-0 bg-light" style="height: 128px;">
            <img class="img-fluid h-100" style="object-fit: contain;" src="https://i.ibb.co/dBLWkm1/suit.png" alt="suit">
          </div>
          <div class="col-12 col-md-auto ps-md-8">
            <h3 class="mb-2 lead fw-bold">Suit Cleaning</h3>
            <p class="mb-8 text-secondary">Wash & Iron</p>
          </div>
        </div>
        <div class="d-flex col-12 col-lg-auto justify-content-between align-items-center flex-lg-column">
          <p class="mb-lg-12 text-end h6 text-info">ksh. 500</p>
          <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
            <button class="btn px-0 py-2">
              <svg width="12" height="2" viewBox="0 0 12 2" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="12" width="2" height="12" transform="rotate(90 12 0)" fill="currentColor"></rect></g></svg>
            </button>
            <input class="form-control px-2 py-4 text-center text-md-end border-0" style="width: 48px;" type="number" placeholder="1" min="0">
            <button class="btn px-0 py-2">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="5" width="2" height="12" fill="currentColor"></rect><rect x="12" y="5" width="2" height="12" transform="rotate(90 12 5)" fill="currentColor"></rect></g></svg>
            </button>
          </div>
        </div>
      </div>
      <div class="row mb-12 align-items-center justify-content-between">
        <div class="col-12 col-lg-auto mb-8 mb-lg-0 d-flex flex-wrap align-items-center">
          <div class="d-flex align-items-center justify-content-center mb-4 mb-lg-0 bg-light" style="height: 128px;">
            <img class="img-fluid h-100" style="object-fit: contain;" src="https://i.ibb.co/kSr0JYx/jacket.png" alt="jacket">
          </div>
          <div class="col-12 col-md-auto ps-md-8">
            <h3 class="mb-2 lead fw-bold">Jacket Cleaning</h3>
            <p class="mb-8 text-secondary">Wash & Fold</p>
          </div>
        </div>
        <div class="d-flex col-12 col-lg-auto justify-content-between align-items-center flex-lg-column">
          <p class="mb-lg-12 text-end h6 text-info">ksh. 50</p>
          <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
            <button class="btn px-0 py-2">
              <svg width="12" height="2" viewBox="0 0 12 2" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="12" width="2" height="12" transform="rotate(90 12 0)" fill="currentColor"></rect></g></svg>
            </button>
            <input class="form-control px-2 py-4 text-center text-md-end border-0" style="width: 48px;" type="number" placeholder="1" min="0">
            <button class="btn px-0 py-2">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="5" width="2" height="12" fill="currentColor"></rect><rect x="12" y="5" width="2" height="12" transform="rotate(90 12 5)" fill="currentColor"></rect></g></svg>
            </button>
          </div>
        </div>
      </div>
      <div class="row mb-12 align-items-center justify-content-between">
        <div class="col-12 col-lg-auto mb-8 mb-lg-0 d-flex flex-wrap align-items-center">
          <div class="d-flex align-items-center justify-content-center mb-4 mb-lg-0 bg-light" style="height: 128px;">
            <img class="img-fluid h-100" style="object-fit: contain;" src="https://i.ibb.co/g74FB2K/Polo.png" alt="Polo">
          </div>
          <div class="col-12 col-md-auto ps-md-8">
            <h3 class="mb-2 lead fw-bold">Polo Cleaning</h3>
            <p class="mb-8 text-secondary">Iron & Fold</p>
          </div>
        </div>
        <div class="d-flex col-12 col-lg-auto justify-content-between align-items-center flex-lg-column">
          <p class="mb-lg-12 text-end h6 text-info">ksh. 50</p>
          <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
            <button class="btn px-0 py-2">
              <svg width="12" height="2" viewBox="0 0 12 2" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="12" width="2" height="12" transform="rotate(90 12 0)" fill="currentColor"></rect></g></svg>
            </button>
            <input class="form-control px-2 py-4 text-center text-md-end border-0" style="width: 48px;" type="number" placeholder="1" min="0">
            <button class="btn px-0 py-2">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="5" width="2" height="12" fill="currentColor"></rect><rect x="12" y="5" width="2" height="12" transform="rotate(90 12 5)" fill="currentColor"></rect></g></svg>
            </button>
          </div>
        </div>
      </div>
      <div class="d-flex flex-wrap mb-10 align-items-center justify-content-between py-6 px-4 px-md-12 bg-info">
        <div class="mb-4 mb-md-0">
          <h5 class="text-white">Subtotal</h5>
          <p class="text-light">Shipping and taxes will be calculated at checkout.</p>
        </div>
        <span class="lead fw-bold text-white">ksh. 900</span>
      </div>
      <div class="text-end"><a class="btn col-12 col-md-auto btn-light mb-4 mb-md-0 me-md-6 text-uppercase" href="{% url 'mama_fua:home' %}">Empty Basket</a><a class="btn col-12 col-md-auto btn-primary" href="{% url 'mama_fua:checkout' %}">Go to Checkout</a></div>
    </div>
  </div>
</section>

<script>
function checkZero(input) {
  if (input.value == 0) {
    $('#removeItemModal').modal('show');

    // Add event listener to remove button in modal
    $('#removeButton').on('click', function() {
      $('#removeItemModal').modal('hide');
    });

    $('#removeItemModal').on('hidden.bs.modal', function () {
      input.value = 1;
    });
  }
}
</script>

{% endblock content %}

mama_fua/templates/mama_fua/cloth_details.html
{% extends 'mama_fua/base.html'%}

{% block title %}Details{% endblock %}

{% block content %}


<section class="py-20 overflow-hidden">
  <div class="container">
    <div class="row mb-24">
      <div class="col-12 col-md-6 mb-8 mb-md-0">
        <div class="position-relative mb-10" style="height: 564px;">
          <img class="img-fluid w-100 h-100" style="object-fit: cover;" src="https://i.ibb.co/qpgTwSf/blanket.png" alt="blanket">
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="ps-lg-20">
          <div class="mb-10 pb-10 border-bottom">
            <span class="text-secondary">Blankets</span>
            <h1 class="mt-2 mb-6 mw-xl">Blanket Cleaning</h1>
            <p class="d-inline-block mb-8 h5 text-info">
              <span>ksh. 300</span>
            </p>
            <p class="mw-md text-secondary">Introducing our premium blanket cleaning service! Our expert team of laundry professionals will take care of your blankets with the utmost care and attention to detail.</p>
          </div>
          <div class="d-flex mb-12">
            <div class="me-6">
              <span class="d-block mb-4 fw-bold text-secondary tetx-uppercase">QTY</span>
              <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
                <button class="btn px-0 py-2">
                  <svg width="12" height="2" viewBox="0 0 12 2" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="12" width="2" height="12" transform="rotate(90 12 0)" fill="currentColor"></rect></g></svg>
                </button>
                <input class="form-control m-0 px-2 py-4 text-center text-md-end border-0" style="width: 48px;" type="number" placeholder="1">
                <button class="btn px-0 py-2">
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity="0.35"><rect x="5" width="2" height="12" fill="currentColor"></rect><rect x="12" y="5" width="2" height="12" transform="rotate(90 12 5)" fill="currentColor"></rect></g></svg>
                </button>
              </div>
            </div>
            <div>
              <span class="d-block mb-4 fw-bold text-secondary text-uppercase">Service</span>
              <select class="form-select border ps-6 pe-10 py-4 fw-bold text-secondary" name="" id="">
                <option value="1">Wash & Iron</option>
                <option value="2">Iron & Fold</option>
                <option value="3">Wash & Dry</option>
              </select>
            </div>
          </div>
          <div class="row mb-14">
            <div class="col-12 col-xl-8 mb-4 mb-xl-0"><a class="btn w-100 btn-primary" href="{% url 'mama_fua:cart' %}">Add to Laundry Basket</a></div>

          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="row mb-16 border-bottom border-2">
        <div class="col-6 col-md-auto"><a class="btn bg-white text-secondary rounded-0 shadow" href="#">Description</a></div>
      </div>
      <h3 class="mb-8 text-info" >Blanket Cleaning Services</h3>
      <p class="mw-2xl text-secondary">Our Blanket Services Include</p>
      <ul class="text-info">
        <li>Thorough cleaning using high-quality detergent to remove all dirt and stains</li>
        <li>Gentle treatment to prevent damage to delicate fabrics</li>
        <li>Special attention to problem areas, such as pet hair and odors</li>
        <li>Softening treatment to restore the plush feel of your blankets</li>
        <li>Optional eco-friendly cleaning methods for those who are environmentally conscious</li>
      </ul>
      <p class="mw-2xl text-secondary">We accept all types of blankets, including wool, cotton, and synthetic fabrics. We recommend washing your blankets every few months to keep them fresh and cozy.</p>
      <p class="mw-2xl text-secondary">Trust us to provide the best care for your blankets, so you can enjoy a good night's sleep!</p>
    </div>
  </div>
</section>


{% endblock content %}

mama_fua/templates/mama_fua/confirm_order.html
{% extends "mama_fua/base.html" %}
{% block title %}Confirm{% endblock %}

{% block content %}


<section class="py-20 bg-light">
  <div class="container">
    <div class="px-4 py-16 py-md-28 px-lg-20 bg-white">
      <h2 class="mb-8">Success !!</h2>
      <h2 class="mb-8">Thank You for Requesting Our Services</h2>
      <p class="mb-16 text-secondary">Service Request Processed Successfully</p>
      <div class="d-flex flex-wrap mb-8 pb-4 border-bottom">
        <div class="me-20">
          <p class="mb-0 text-secondary">Service Number</p>
          <p class="text-info fw-bold">XYZ0864395</p>
        </div>
        <div class="me-auto">
          <p class="mb-0 text-secondary">Date</p>
          <p class="text-info fw-bold">Tuesday 04, 2023</p>
        </div>
      </div>
      <div class="row mb-8">
        <div class="col-12 col-lg-2 mb-8 mb-lg-0">
          <div class="d-flex align-items-center justify-content-center bg-light-light" style="height: 288px;">
            <img class="img-fluid" style="height: 256px; object-fit: cover;" src="https://i.ibb.co/qpgTwSf/blanket.png" alt="blanket">
          </div>
        </div>
        <div class="col-12 col-lg-10">
          <div class="d-flex mb-8 mb-md-16">
            <div class="me-auto">
              <h3 class="lead fw-bold">Blanket Cleaning</h3>
              <p class="text-secondary">Wash & Fold</p>
            </div>
            <span class="h5 text-info">ksh. 300</span>
          </div>
          <div class="row">
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Delivery Address</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">Heri Homes</p>
              <p class="mb-0 text-secondary">House No. B6</p>
            </div>
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Shipping Informations</p>
              <p class="mb-0 text-secondary">moses@musemi.com</p>
              <p class="mb-0 text-secondary">0712345678</p>
            </div>
            <div class="col-12 col-lg-auto">
              <p class="mb-6 fw-bold">Payment Informations</p>
              <p class="mb-0 text-secondary">Mpesa</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">07012345678</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-8">
        <div class="col-12 col-lg-2 mb-8 mb-lg-0">
          <div class="d-flex align-items-center justify-content-center h-72 bg-light-light" style="height: 288px;">
            <img class="img-fluid" style="height: 256px; object-fit: cover;" src="https://i.ibb.co/dBLWkm1/suit.png" alt="suit">
          </div>
        </div>
        <div class="col-12 col-lg-10">
          <div class="d-flex mb-8 mb-md-16">
            <div class="me-auto">
              <h3 class="lead fw-bold">Suit Cleaning</h3>
              <p class="text-secondary">Wash & Iron</p>
            </div>
            <span class="h5 text-info">ksh. 500</span>
          </div>
          <div class="row">
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Delivery Address</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">Heri Homes</p>
              <p class="mb-0 text-secondary">House No. B6</p>
            </div>
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Shipping Informations</p>
              <p class="mb-0 text-secondary">moses@musemi.com</p>
              <p class="mb-0 text-secondary">0712345678</p>
            </div>
            <div class="col-12 col-lg-auto">
              <p class="mb-6 fw-bold">Payment Informations</p>
              <p class="mb-0 text-secondary">Mpesa</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">07012345678</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-8">
        <div class="col-12 col-lg-2 mb-8 mb-lg-0">
          <div class="d-flex align-items-center justify-content-center h-72 bg-light-light" style="height: 288px;">
            <img class="img-fluid" style="height: 256px; object-fit: cover;" src="https://i.ibb.co/kSr0JYx/jacket.png" alt="jacket">
          </div>
        </div>
        <div class="col-12 col-lg-10">
          <div class="d-flex mb-8 mb-md-16">
            <div class="me-auto">
              <h3 class="lead fw-bold">Jacket Cleaning</h3>
              <p class="text-secondary">Wash & Fold</p>
            </div>
            <span class="h5 text-info">ksh. 50</span>
          </div>
          <div class="row">
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Delivery Address</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">Heri Homes</p>
              <p class="mb-0 text-secondary">House No. B6</p>
            </div>
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Shipping Informations</p>
              <p class="mb-0 text-secondary">moses@musemi.com</p>
              <p class="mb-0 text-secondary">0712345678</p>
            </div>
            <div class="col-12 col-lg-auto">
              <p class="mb-6 fw-bold">Payment Informations</p>
              <p class="mb-0 text-secondary">Mpesa</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">07012345678</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-8">
        <div class="col-12 col-lg-2 mb-8 mb-lg-0">
          <div class="d-flex align-items-center justify-content-center h-72 bg-light-light" style="height: 288px;">
            <img class="img-fluid" style="height: 256px; object-fit: cover;" src="https://i.ibb.co/g74FB2K/Polo.png" alt="Polo">
          </div>
        </div>
        <div class="col-12 col-lg-10">
          <div class="d-flex mb-8 mb-md-16">
            <div class="me-auto">
              <h3 class="lead fw-bold">Polo Cleaning</h3>
              <p class="text-secondary">Wash & Fold</p>
            </div>
            <span class="h5 text-info">ksh. 50</span>
          </div>
          <div class="row">
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Delivery Address</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">Heri Homes</p>
              <p class="mb-0 text-secondary">House No. B6</p>
            </div>
            <div class="col-12 col-lg-auto me-md-10 mb-6 mb-lg-0">
              <p class="mb-6 fw-bold">Shipping Informations</p>
              <p class="mb-0 text-secondary">moses@musemi.com</p>
              <p class="mb-0 text-secondary">0712345678</p>
            </div>
            <div class="col-12 col-lg-auto">
              <p class="mb-6 fw-bold">Payment Informations</p>
              <p class="mb-0 text-secondary">Mpesa</p>
              <p class="mb-0 text-secondary">Moses Musemi</p>
              <p class="mb-0 text-secondary">07012345678</p>
            </div>
          </div>
        </div>
      </div>
      <div class="mb-4">
        <div class="py-3 px-10 bg-light rounded-pill">
          <div class="d-flex justify-content-between">
            <span class="fw-bold">Subtotal</span>
            <span class="fw-bold">ksh. 900</span>
          </div>
        </div>
        <div class="py-3 px-10 rounded-pill">
          <div class="d-flex justify-content-between">
            <span class="fw-bold">Shipping</span>
            <span class="fw-bold">ksh. 20</span>
          </div>
        </div>
        <div class="py-3 px-10 rounded-pill">
          <div class="d-flex justify-content-between">
            <span class="lead fw-bold">Services Total</span>
            <span class="fw-bold">ksh. 920</span>
          </div>
        </div>
      </div>
      <div class="text-end"><a class="btn btn-primary col-12 col-md-auto text-uppercase" href="{% url 'mama_fua:home' %}">Go To Home Page</a></div>
    </div>
  </div>
</section>


{% endblock content %}